# fluentd-s3-configmap.yml

---
# create the fluentd.conf config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: fluentdlogging
data:
  fluent.conf: |
    @include "#{ENV['FLUENTD_SYSTEMD_CONF'] || 'systemd'}.conf"
    @include "#{ENV['FLUENTD_PROMETHEUS_CONF'] || 'prometheus'}.conf"
    @include kubernetes.conf
    @include conf.d/*.conf

    <match **>
      # docs: https://docs.fluentd.org/v0.12/articles/out_s3
      # note: this configuration relies on the nodes have an IAM instance profile with access to your S3 bucket
      @type s3
      @id out_s3
      @log_level info
      s3_bucket "#{ENV['S3_BUCKET_NAME']}"
      s3_region "#{ENV['S3_BUCKET_REGION']}"
      s3_object_key_format %{path}/%Y/%m/%d/cluster-log-%{index}.%{file_extension}
      path "cluster-1"
      <inject>
        time_key time
        tag_key tag
        localtime false
      </inject>
      <buffer>
        @type file
        path /var/log/fluentd-buffers/s3.buffer
        timekey 3600
        timekey_use_utc true
        chunk_limit_size 256m
      </buffer>
    </match>
