# fluentd-s3-secrets.yml

---
# create secrets for AWS access
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-fluentd
  namespace: fluentdlogging
stringData:
  aws_access_key_id: '<AWS_ACCESS_KEY>'
  aws_secret_access_key: '<AWS_SECRET_ACCESS_KEY>'
