# pod2.yaml

apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
  labels:
    app: basic-pod
spec:
  containers:
    - name: server
      image: nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080
