apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: test-image-web
    name: test-web
    volumeMounts:
    - mountPath: /data
      name: shared-volume
  - image: test-image-logger
    name: test-logger
    volumeMounts:
    - mountPath: /logs
      name: shared-volume
  volumes:
  - name: shared-volume
    emptyDir: {}
