apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-test-01
spec:
  capacity:
    storage: 256M
  accessModes:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/pvol_test
