heat_template_version: 2016-10-14

description: |
  The heat template is used to demo the autoscaling and autohealing.
parameters:
  keypair:
    type: string
    default: dans-key
  webserver_image_id:
    description: Need to be a cirros image.
    type: string
    default: 0da75c8a-787d-48cd-bb74-e979fc5ceb58
  webserver_flavor_id:
    type: string
    default: c1.c1r1
  webserver_network_id:
    type: string
    default: 452fc8b7-218d-4279-99b2-3d46f9d016b7
  webserver_sg_ids:
    description: Security groups that allows TCP 22 access
    type: comma_delimited_list
    default: ["9763cd61-4bc5-4c4d-8962-495d243e57e2"]
  vip_subnet_id:
    description: Should be a subnet of webserver_network_id
    type: string
    default: 0d10e475-045b-4b90-a378-d0dc2f66c150
  public_network:
    description: Public network name, could get by 'openstack network list --external'
    type: string
    default: public-net
  scaleup_cpu_threshold:
    type: number
    default: 80
  scaledown_cpu_threshold:
    type: number
    default: 5

resources:
  autoscaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 4
      resource:
        type: OS::LB::Server
        properties:
          keypair: {get_param: keypair}
          image_id: {get_param: webserver_image_id}
          flavor_id: {get_param: webserver_flavor_id}
          network_id: {get_param: webserver_network_id}
          sg_ids: {get_param: webserver_sg_ids}
          public_network: {get_param: public_network}
          pool_id: {get_resource: loadbalancer_pool}
          metadata: {"metering.stack": {get_param: "OS::stack_id"}}
  loadbalancer:
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: {get_param: vip_subnet_id}
      name: webserver_lb
  loadbalancer_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_network}
      port_id: {get_attr: [loadbalancer, vip_port_id]}
  listener:
    type: OS::Octavia::Listener
    properties:
      name: webserver_listener
      protocol: HTTP
      protocol_port: 80
      loadbalancer: {get_resource: loadbalancer}
  loadbalancer_pool:
    type: OS::Octavia::Pool
    properties:
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      listener: {get_resource: listener}
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: autoscaling_group}
      scaling_adjustment: 1
      cooldown: 60
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: autoscaling_group}
      scaling_adjustment: -1
      cooldown: 60
  ceilometer_cpu_high_alarm:
    type: OS::Aodh::Alarm
    properties:
      meter_name: cpu_util
      period: 60
      evaluation_periods: 1
      statistic: avg
      comparison_operator: gt
      threshold: 5.0
      alarm_actions:
        - {get_attr: [ scaleup_policy, alarm_url ] }
        # - str_replace:
        #     template: trust+url
        #     params:
        #       url: {get_attr: [scaleup_policy, signal_url]}
      repeat_actions: false
      matching_metadata: { 'metadata.user_metadata.stack': { get_param: "OS::stack_id" } }
  ceilometer_cpu_low_alarm:
    type: OS::Aodh::Alarm
    properties:
      meter_name: cpu_util
      period: 60
      evaluation_periods: 1
      statistic: avg
      comparison_operator: lt
      threshold: 1.0
      alarm_actions:
        - {get_attr: [ scaledown_policy, alarm_url ] }
        # - str_replace:
        #     template: trust+url
        #     params:
        #       url: {get_attr: [scaledown_policy, signal_url]}
      repeat_actions: false
      matching_metadata: { 'metadata.user_metadata.stack': { get_param: "OS::stack_id" } }

outputs:
  scale_up_url:
    value: {get_attr: [scaleup_policy, alarm_url]}
  scale_down_url:
    value: {get_attr: [scaledown_policy, alarm_url]}
  scale_up_signal_url:
    value: {get_attr: [scaleup_policy, signal_url]}
  scale_down_signal_url:
    value: {get_attr: [scaledown_policy, signal_url]}
  lb_ip:
    value: {get_attr: [loadbalancer_public_ip, floating_ip_address]}
