---
#
# Play 1 - Create 'x' instances in Openstack based on 'count' var
#
- name: Deploy multiple duplicate cloud instances in OpenStack
  hosts: localhost

  vars:
    image: ubuntu-18.04-x86_64
    network: example-net
    key_name: example-key
    flavor: c1.c1r1
    security_groups: example-sg
    count: 3

  tasks:
    - name: Connect to the Catalyst Cloud
      # assume RC file has already been sourced
      os_auth:

    - name: Launch web instances
      os_server:
        state: present
        name: test0{{ item }}
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        key_name: "{{ key_name }}"
        wait: true
        network: "{{ network }}"
        security_groups: "{{ security_groups }}"
        auto_ip: true
      loop: "{{ range(1, count + 1) | list }}"
      register: newnodes

    - name: Create in-memory Ansible inventory
      add_host:
        name: "{{ item.server.public_v4 }}"
        groups: created_nodes
        ansible_user: ubuntu
        instance_name: "{{ item.server.name }}"
      loop: "{{ newnodes.results }}"

#
# Play 2 - Configure nodes from in-memory inventory
#
- name: Configure nodes
  hosts: created_nodes
  become: true
  gather_facts: false

  tasks:
    - name: Wait for SSH banners
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Install apps
      apt:
        state: present
        name: ["git", "htop"]
        update_cache: true

    - name: Pause play to interact with the servers
      pause:
        prompt: "Playbook paused... hit <enter> to continue or <ctrl-c a> to abort"

#
# Play 3 - Destroy nodes
#
- name: Destroy nodes
  hosts: localhost

  tasks:
    - name: Destroy instances
      os_server:
        state: absent
        name: "{{ hostvars.item.instance_name }}"
      loop: "{{ groups.created_nodes }}"
